### PR TITLE
Fix camelcase consistency for mempool calls

### PR DESCRIPTION
**Pull request by johnbailon**
Small fix on camelCase consistency for mempool call.

### CODE REVIEW

**Comment by ruimarinho** [comment]
I see that Travis tests are failing but it's unrelated to your PR (should have used a fixed Docker image). How angry does this inconsistency makes you feel :-)? This would require a major version due to the breaking change..

**Comment by johnbailon** [comment]
@ruimarinho haha, don't sweat it. I ran into it and thought it should make for a nice pull request. Feel free to wait for other fixes to make the major version bump worth it.

**Comment by ruimarinho** [comment]
This will likely be merged when the returned numbers are changed to be returned as strings.

**Comment by ruimarinho** [comment]
@johnbailon I'm more inclined to rename the other methods to `Mempool` instead of `MemPool`.

**Comment by johnbailon** [comment]
@ruimarinho why so? Do note that bitcoind's docs use `MemPool`.

**Comment by ruimarinho** [comment]
@johnbailon most people are using `mempool` or `Mempool`:

- https://github.com/bitcoin/bitcoin/pull/6654
- https://github.com/bitcoin/bitcoin/pull/6915
- https://blockchain.info/charts/mempool-size
- https://themerkle.com/what-is-the-bitcoin-mempool/

Looks like the only place where `MemPool` is used is in the [bitcoin developer reference docs](https://bitcoin.org/en/developer-reference#getmempoolinfo).

**Comment by promag** [comment]
The fix should be s/MemPool/Mempool.

**Pull request closed without merging**
